classdef chooseLineWidthMarkerSize < wizardpage
    properties
        fSize = 11
    end


    methods
        function obj = chooseLineWidthMarkerSize(parentWizard)
            obj@wizardpage(parentWizard);

            % Must place all UI elements in the structure obj.graphics handles so that they are
            % deleted when the object is deleted. See the wizardpage abstract class destructor.
            obj.graphicsHandles.textBox1 = annotation(obj.hPagePanel, 'textbox', ...
            'Units', 'pixels', ...
            'Position', [50,100,230,19] , ...
            'EdgeColor', 'none', ...
            'VerticalAlignment', 'middle',...
            'FontSize', obj.fSize, ...
            'FitBoxToText','off', ...
            'String', 'Enter a line width:');

            editBoxTag1 = 'linewidth';
            obj.graphicsHandles.editBox1 = uicontrol(obj.hPagePanel,'Style','edit', ...
            'Units', 'pixels', ...
            'Tag', editBoxTag1, ...
            'Position', [230,100,30,19] , ...
            'FontSize', obj.fSize, ...
            'String', '', ...
            'CallBack', @obj.validateEditBox);

            obj.graphicsHandles.textBox2 = annotation(obj.hPagePanel, 'textbox', ...
            'Units', 'pixels', ...
            'Position', [50,150,230,19] , ...
            'EdgeColor', 'none', ...
            'VerticalAlignment', 'middle',...
            'FontSize', obj.fSize, ...
            'FitBoxToText','off', ...
            'String', 'Enter a marker size:');

            editBoxTag2 = 'markersize';
            obj.graphicsHandles.editBox2 = uicontrol(obj.hPagePanel,'Style','edit', ...
            'Units', 'pixels', ...
            'Tag', editBoxTag2, ...
            'Position', [230,150,30,19] , ...
            'FontSize', obj.fSize, ...
            'String', '', ...
            'CallBack', @obj.validateEditBox);


            % Note that structure field has the same name as the tag. See how this is 
            % is used in the callback function "validateColorBox", below.
            obj.validAnswersStruct.(editBoxTag1)=false;
            obj.validAnswersStruct.(editBoxTag2)=false;

            % By default no next button unless edit box is valid
            obj.hNextButton.Enable = 'off'; 

            % Attempt to re-apply cached data
            obj.reapplyCachedData

        end

        % TODO -- some way to validate separately each edit box. Then a single validate prop to send out. 
        function validateEditBox(obj,src,~)

            % Ensure this is a scalar
            out = str2num(src.String);
            if isempty(out)
                src.String = '';
                obj.isValid = false;
                return
            end

            %Store these in the cachedData
            obj.cacheVals(src)
        end %validateColorBox


    end %methods

end %classdef