classdef chooseStyle < wizardpage
    properties
        fSize = 11
    end


    methods
        function obj = chooseStyle(parentWizard)
            obj@wizardpage(parentWizard);

            % Must place all UI elements in the structure obj.graphics handles so that they are
            % deleted when the object is deleted. See the wizardpage abstract class destructor.
            obj.graphicsHandles.textBox1 = annotation(obj.hPagePanel, 'textbox', ...
            'Units', 'pixels', ...
            'Position', [20,300,220,19] , ...
            'EdgeColor', 'none', ...
            'VerticalAlignment', 'middle',...
            'FontSize', obj.fSize, ...
            'FitBoxToText','off', ...
            'String', 'Select line style:');

            obj.graphicsHandles.popup1 = uicontrol(obj.hPagePanel,'Style','popupmenu', ...
            'Units', 'pixels', ...
            'Tag', 'linestyle', ...
            'Position', [200,300,100,19] , ...
            'FontSize', obj.fSize, ...
            'String', {'-',':','-.','--','none'},...
            'Callback', @obj.cacheVals); % Note: we cache values when there is a UI event

            obj.graphicsHandles.textBox2 = annotation(obj.hPagePanel, 'textbox', ...
            'Units', 'pixels', ...
            'Position', [20,270,220,19] , ...
            'EdgeColor', 'none', ...
            'VerticalAlignment', 'middle',...
            'FontSize', obj.fSize, ...
            'FitBoxToText','off', ...
            'String', 'Select marker style:');

            obj.graphicsHandles.popup2 = uicontrol(obj.hPagePanel,'Style','popupmenu', ...
            'Units', 'pixels', ...
            'Tag', 'markerstyle', ...
            'Position', [200,270,100,19] , ...
            'FontSize', obj.fSize, ...
            'String', {'.','o','x','+','*','s','d','v'},...
            'Callback', @obj.cacheVals); % Note: we cache values when there is a UI event


            % If there is already a value in the structure we re-use it
            obj.reapplyCachedData;

        end %chooseStyle

    end %methods

end %classdef